### ISSUE TITLE
Generation without using a file

### ISSUE THREAD

**Issue by Rachneet** [facebookresearch/access#31]
Hi Louis,

I am trying to input a single sentence for simplification instead of a file. But I run into the following exception
`Exception: Could not infer language pair, please provide it explicitly` 

Since you explicitly copy the input complex file to 'exp_dir' and create a dummy simple file there, how should we tackle this if I do not want to deal with files here?

**Comment by louismartin** [comment]
Hi,

Yes this is due to the fact that we use the `fairseq-generate` interface ([see this line](https://github.com/facebookresearch/access/blob/7b61fbf0bad665798d662e0a90d2a0e451367df6/access/fairseq/base.py#L178)).
Feeding a string instead of a file would be possible by adapting the code to use `fairseq-interactive` instead but it would require some modifications.
Feel free to improve and submit a pull request if that's something that you are willing to do.

**Comment by Rachneet** [comment]
Thanks. I will check this out.

**Comment by louismartin** [comment]
Closing for now, feel free to comment or open again if you are still having issues.
