### ISSUE TITLE
How to use `DependencyTreeDepthRatioPreprocessor` during generation?

### ISSUE THREAD

**Issue by Nntraveler** [facebookresearch/access#32]
I find that in `scripts/train.py`, it is possible to modify `DependencyTreeDepthRatioPreprocessor` values which I guess may help to split complex sentence into several simple sentences according to the paper. However, it was removed in `generate.py`.
Is it possible to add this ratio into generation phase so that I can use it to split sentence with deep dependency tree? Thanks!

**Comment by louismartin** [comment]
Hello @Nntraveler and thanks for the question.
Yes this is because we didn't use the DependencyTreeDepthRatioPreprocessor in the final model as explained in the paper so it is not possible to control using this preprocessor.
You can check [MUSS models](https://github.com/facebookresearch/muss/) which should have this preprocessor.
